version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    build:
      context: ../menu_project
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  static_value:
  media_value:
  postgres_data:
